project_id = "hogejkqzynixmjwodkoi"

[functions.courier-balance]
verify_jwt = false

[functions.get-client-info]
verify_jwt = false

[functions.fetch-meta-ads]
verify_jwt = false

[functions.track-landing-event]
verify_jwt = false

[functions.submit-landing-order]
verify_jwt = false

[functions.fb-conversions-api]
verify_jwt = false

[functions.track-partial-order]
verify_jwt = false

[functions.sync-orders]
verify_jwt = false

[functions.order-api]
verify_jwt = false

[functions.courier-locations]
verify_jwt = false

[functions.courier-webhook]
verify_jwt = false

[functions.product-feed]
verify_jwt = false
