
ALTER TABLE public.landing_page_events 
ADD COLUMN IF NOT EXISTS utm_source text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS utm_medium text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS utm_campaign text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS utm_content text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS utm_term text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS scroll_depth integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS device_type text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS screen_width integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS screen_height integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS browser text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS os text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS country text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS city text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS session_id text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS time_on_page integer DEFAULT NULL;
